### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by SheltonLiu-N** [ThuCCSLab/Awesome-LM-SSP#10]
| Title | Link  | Code |   Venue |  Classification |  Model | Comment | 
| ---- |---- |---- |---- |---- |----|----| 
| AdaShield: Safeguarding Multimodal Large Language Models from Structure-based Attack via Adaptive Shield Prompting |  https://arxiv.org/abs/2403.09513 | https://github.com/rain305f/AdaShield  | arXiv'24  | A1. Jailbreak | VLM  | VLM Jailbreak Defense |

**Comment by ThuCCSLab** [comment]
Thanks for the great work! 
We have appended the list, pls check it, thanks!

**Comment by SheltonLiu-N** [comment]
Thank you!
