### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by liuyixin-louis** [ThuCCSLab/Awesome-LM-SSP#14]
Thank you for this great paper collection! It will be my pleasure if my work can be included in the repo; thanks!  

Title | Link | Code | Venue | Classification | Model | Comment
-- | -- | -- | -- | -- | -- | --
MetaCloak: Preventing Unauthorized Subject-driven Text-to-image Diffusion-based Synthesis via Meta-learning | https://arxiv.org/abs/2311.13127 | https://github.com/liuyixin-louis/MetaCloak | CVPR'24 Oral | B1. Adversarial Examples | Diffusion | a more robust protective perturbation framework for safeguarding portrait against customized diffusion models training

**Comment by ThuCCSLab** [comment]
Great work! We have added this paper, please check it, thanks!

**Comment by liuyixin-louis** [comment]
Perfect! Thanks again for this great collection.
