### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by ShangQingTu** [ThuCCSLab/Awesome-LM-SSP#17]
Thank you for this great paper collection! I would be delighted if my work could be incorporated into the repository; thank you!

<!DOCTYPE html><figure class="md-table-fig" cid="n403" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
Title | Link | Code | Venue | Classification | Model | Comment
-- | -- | -- | -- | -- | -- | --
DICE: Detecting In-distribution Contamination in LLM's Fine-tuning Phase for Math Reasoning | https://arxiv.org/abs/2406.04197 | https://github.com/THU-KEG/DICE | arXiv'24 | C1. Contamination | LLM | A novel contamination detection method  which leverages the internal states of LLMs to detect data contamination in fine-tune stage for math reasoning.
KoLA: Carefully Benchmarking World Knowledge of Large Language Models | https://openreview.net/forum?id=AqN23oqraW | https://kola.xlore.cn/ | ICLR'24 | C1. Contamination | LLM | A carefully designed evolving benchmark for evaluating LLMs' world knowledge. KoLA benchmark is evolving so that it can avoid the data contamination issue.

</figure>

**Comment by ThuCCSLab** [comment]
Hi Shangqing, we have added these excellent papers to the list, as well as `WaterBench`, please check it, thanks!

**Comment by ShangQingTu** [comment]
Thank you very much!
