### ISSUE TITLE
Kindly request the inclusion 

### ISSUE THREAD

**Issue by Shilin-LU** [ThuCCSLab/Awesome-LM-SSP#19]
Thank you for this great paper collection! I would be delighted if my work could be incorporated into the repository; thank you!

Title | Link | Code | Venue | Classification | Model | Comment
-- | -- | -- | -- | -- | -- | --
MACE: Mass Concept Erasure in Diffusion Models | https://arxiv.org/abs/2403.06135 | https://github.com/Shilin-LU/MACE | CVPR'24 | C8. Unlearning | Diffusion | -

**Comment by ThuCCSLab** [comment]
Hi Shilin, congrats on your excellent work! We have added the paper to the list, please check it~

**Comment by Shilin-LU** [comment]
Thank you so much! Just noticed the email, sorry for the late reply.
