### ISSUE TITLE
Complementing CodeGen LLM

### ISSUE THREAD

**Issue by EmmetWilliam** [ThuCCSLab/Awesome-LM-SSP#21]
Thanks for your awesome collection of awesome paper resources!

But I wonder will you consider more _SSP_ research on CodeGen LLMs  (or whether they should be archived in this collection).

Especially works targeting early-stage models in LLM era, here are some examples, 

- [SP 22] Asleep at the Keyboard? Assessing the Security of GitHub Copilot’s Code Contributions
- [CCS 23] Large Language Models for Code: Security Hardening and Adversarial Testing, etc.

Thanks again!

**Comment by ThuCCSLab** [comment]
Hi! Thanks for your suggestion.

Actually we have collected some papers about CodeGen LLM, you can find some papers (e.g., in C.2 Copyright) with green badges `codeGen`.

But recently, we found it difficult to generalize these works into our category, so we did not continue the collection. 

However, you are welcome to provide some clearly categorized and representative work, through pulling requests or issues.

Best wishes~
