### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by DYR1** [ThuCCSLab/Awesome-LM-SSP#22]
Thank you for this great paper collection! I would be delighted if my work could be incorporated into the repository; thank you!

|   Title    | Link | Code | Venue | Classification | Model |  Comment |
|-----------------|-----------------|-----------------|-----------------|-----------------|-----------------|-----------------|
| MoGU: A Framework for Enhancing Safety of Open-Sourced LLMs While Preserving Their Usability    | https://arxiv.org/abs/2405.14488    |  https://huggingface.co/yrdu & https://github.com/DYR1/MoGU   | Arxiv    | A2. Alignment     | LLMs    | - |

**Comment by ThuCCSLab** [comment]
Hi Yanrui!
We have added this paper to the list, pls check it~

**Comment by DYR1** [comment]
Thank you very much!
