### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by 99starman** [ThuCCSLab/Awesome-LM-SSP#23]
Thank you for this great paper collection! I would be delighted if our work could be incorporated into the repository; thank you!
| Title | Link | Code | Venue | Classification | Model | Comment |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| Training Socially Aligned Language Models on Simulated Social Interactions | https://openreview.net/forum?id=NddKiWtdUm | https://github.com/agi-templar/Stable-Alignment | ICLR '24 | A2. Alignment | LLMs | - |

**Comment by ThuCCSLab** [comment]
Hi Ruixin~This excellent paper has been added to the [list](https://github.com/ThuCCSLab/Awesome-LM-SSP/blob/98f94cc12f3444ee748f3a87a279672d69c93d27/collection/paper/safety/alignment.md?plain=1#L32), please check it.

Thanks for your support!

**Comment by 99starman** [comment]
Thank you!
