### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by haowang-cqu** [ThuCCSLab/Awesome-LM-SSP#24]
Thank you for this great paper collection! I would be delighted if my work could be incorporated into the repository; thank you!

Title | Link | Code | Venue | Classification | Model | Comment
-- | -- | -- | -- | -- | -- | --
EvilEdit: Backdooring Text-to-Image Diffusion Models in One Second| https://openreview.net/forum?id=ibEaSS6bQn | https://github.com/haowang-cqu/EvilEdit | MM'24 | B2. Poison & Backdoor | Diffusion |

**Comment by ThuCCSLab** [comment]
Hi Hao! This great work has been included in our list, thanks for your sharing!

**Comment by haowang-cqu** [comment]
Thank you very much!
