### ISSUE TITLE
Inclusion of new paper

### ISSUE THREAD

**Issue by Junjie-Chu** [ThuCCSLab/Awesome-LM-SSP#25]
👍 Thank you for creating and maintaining such a great repository. I found that these works have not been included and hope they can be added.

| Title | Link  | Code |   Venue |  Classification |  Model | Comment | 
| ---- |---- |---- |---- |---- |----|----| 
| Formalizing and Benchmarking Prompt Injection Attacks and Defenses |  [arxiv](https://arxiv.org/abs/2310.12815) | [github](https://github.com/liu00222/Open-Prompt-Injection)  | USENIX'24 |  A7. Prompt Injection | LLM  | Benchmark |

**Comment by ThuCCSLab** [comment]
Hi Junjie!

We have added this great paper. Thanks for your recommendation! 😄
