### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by Ahmedfrkh** [ThuCCSLab/Awesome-LM-SSP#26]
Could you please add the following 3 privacy-related works? I believe they are very valuable. Thank you for maintaining this great repo!

| Title | Link | Code | Venue | Classification | Model | Comment |
|----------|----------|----------|----------|----------|----------|----------|
|    PII-Compass: Guiding LLM training data extraction prompts towards the target PII via grounding    |    [Link](https://arxiv.org/abs/2407.02943)    |    coming soon    |    ACL 2024    |    C3. Data Reconstruction    |    LLM    |    -    |
|    ObfuscaTune: Obfuscated Offsite Fine-tuning and Inference of Proprietary LLMs on Private Datasets    |    [Link](https://arxiv.org/abs/2407.02960)    |    coming soon    |    ArXiv (under review)    |    C6. Privacy-Preserving Computation    |    LLM    |    -    |
|    IncogniText: Privacy-enhancing Conditional Text Anonymization via LLM-based Private Attribute Randomization    |    [Link](https://arxiv.org/abs/2407.02956)    |    coming soon    |    ArXiv (under review)    |    C0. General    |    LLM    |    -    |

**Comment by Ahmedfrkh** [comment]
Found out that they are already there, thanks.

**Comment by ThuCCSLab** [comment]
Great works! 

Feel free to recommend papers! 😄
