### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by Manu21JC** [ThuCCSLab/Awesome-LM-SSP#30]
Thank you for maintaining this awesome paper collection. I would be delighted if my work could be incorporated into the repository; thank you! 
| Title | Link  | Code |   Venue |  Classification |  Model | Comment |
| ---- |---- |---- |---- |---- |----|----| 
| Dormant: Defending against Pose-driven Human Image Animation | https://arxiv.org/abs/2409.14424 | https://github.com/Manu21JC/Dormant | arXiv'24 | C2. Copyright | Diffusion | Preventing unauthorized human image animation |

**Comment by ThuCCSLab** [comment]
Hi!

Thanks for your sharing! We have added your excellent paper to the list, pls check it.

Best wishes,
LM-SSP Team
