### ISSUE TITLE
关于分类的问题

### ISSUE THREAD

**Issue by uuutmtm** [ThuCCSLab/Awesome-LM-SSP#31]
目前的分类有三种，safety、security和privacy。为什么分为这三类？请问privacy是否应该归于safety或者security中？如果是，那么应该归于哪一类？

**Comment by ThuCCSLab** [comment]
Hi!

关于safety和security的区别，可以参考这篇文章：https://arxiv.org/abs/2405.19524
我们认为，privacy是单独一类。

谢谢！
LM-SSP Team
