### ISSUE TITLE
Inclusion of a paper

### ISSUE THREAD

**Issue by KKNakkav2** [ThuCCSLab/Awesome-LM-SSP#33]
Dear Team, 

Can you please add the work, "PII-Scope: A Benchmark for Training Data PII Leakage Assessment in LLMs" available at https://arxiv.org/abs/2410.06704  to the `privacy/data reconstruction` section.

Thanks

**Comment by ThuCCSLab** [comment]
Hi!

Thanks for your sharing! We have added your excellent paper to the list, pls check it.

Best wishes,
LM-SSP Team

**Comment by KKNakkav2** [comment]
Thank you!
