### ISSUE TITLE
Missing [RAG] tag

### ISSUE THREAD

**Issue by haowang-cqu** [ThuCCSLab/Awesome-LM-SSP#34]
https://github.com/ThuCCSLab/Awesome-LM-SSP/blob/36dbb00c47a9b7bb58a6b010bf93a5f25924f50c/collection/paper/safety/prompt_injection.md?plain=1#L3

Should this article have the [RAG] tag added?

**Comment by ThuCCSLab** [comment]
Hi Hao!

We have added the `RAG` tag, thanks for your correction!

Best wishes,
LM-SSP Team

**Comment by haowang-cqu** [comment]
Thank you for actively maintaining this repository; it has been incredibly helpful to me.
