### ISSUE TITLE
Paper Inclusion Request

### ISSUE THREAD

**Issue by Lucas-TY** [ThuCCSLab/Awesome-LM-SSP#35]
Hi team,

Could you please add the work titled *"You Know What I'm Saying: Jailbreak Attack via Implicit Reference"*, available at [arXiv](https://arxiv.org/abs/2410.03857), to the paper/safety/jailbreak section? With the GitHub link: [GitHub Repository](https://github.com/Lucas-TY/llm_Implicit_reference).

**Comment by ThuCCSLab** [comment]
Hi!

Thanks for your sharing! This nice paper has been included in the list, please check it.

LM-SSP Team

**Comment by Lucas-TY** [comment]
Thanks
