### ISSUE TITLE
readme出现问题了嘛

### ISSUE THREAD

**Issue by OneStepAndTwoSteps** [ThuCCSLab/Awesome-LM-SSP#36]
readme 论文的标题不显示了
![image](https://github.com/user-attachments/assets/402ad234-fb0f-4a9c-9b21-541c3b10f5aa)

**Comment by eggry** [comment]
Thanks for your feedback!
We have fixed this issue in https://github.com/ThuCCSLab/Awesome-LM-SSP/commit/23d51961b2e5275b060c3318341ce6631a825da3 .
