### ISSUE TITLE
Kindly request the inclusion

### ISSUE THREAD

**Issue by AmenRa** [ThuCCSLab/Awesome-LM-SSP#37]
Thank you for this great repo! I would be delighted if our work could also be included.

- Title: GuardBench: A Large-Scale Benchmark for Guardrail Models
- Venue: EMNLP 2024
- Paper: https://aclanthology.org/2024.emnlp-main.1022.pdf
- Code: https://github.com/AmenRa/guardbench
- Classification: toolkit
- Model: guardrail models
- Tags: guardrail models, safety, benchmark, evaluation

**Comment by ThuCCSLab** [comment]
Hi!

Congrats on your excellent work! 
We have included this paper into `toolkit` of our list, please check it!

Best,
LM-SSP Team

**Comment by AmenRa** [comment]
Great, thanks! :)
