### ISSUE TITLE
Kindly Request the Inclusion

### ISSUE THREAD

**Issue by Raytsang123** [ThuCCSLab/Awesome-LM-SSP#39]
Thank you for this awesome paper collection! Could you please add the following survey on the security, privacy, and safety of LLM-based agents? Thank you!

| Title | Link | Classification | Model |
| ------ | ---- | ------ | ----- |
| Navigating the Risks: A Survey of Security, Privacy, and Ethics Threats in LLM-Based Agents  | [arxiv](https://arxiv.org/abs/2411.09523) | Survey | LLM, Agent |

**Comment by ThuCCSLab** [comment]
Hi!

We have included this excellent survey to the list, thanks for your support!

Best wishes,
LM-SSP Team
